image: electronuserland/electron-builder:wine

cache:
  paths:
    - node_modules/

before_script:
  - npm install

stages:
  - deploy

publish:
  stage: deploy
  when: manual
  script:
    - npm run build
    - curl --request POST --header "Private-Token:MAzPbYT-xgaUgx2Nc4di" --form "file=/builds/Rett/coordinator/build/coordinator Setup $Tag.exe" "https://gitlab.com/Rett/api/v4/projects/sync/uploads"