image: electronuserland/builder:wine

cache:
  paths:
    - node_modules/

before_script:
  - npm install -g n
  - n 10.16.3
  - npm install

stages:
  - deploy

publish:
  stage: deploy
  only:
    - tags
  script:
    - npm run build
    - newline=$'\n'
    - filename="coordinator Setup $CI_COMMIT_REF_NAME.exe"
    - content=$(curl --request POST --header "Private-Token:MAzPbYT-xgaUgx2Nc4di" --form "file=@/builds/Rett/coordinator/build/${filename}" "https://gitlab.com/api/v4/projects/18471086/uploads")
    - echo ${content}
    - url=$(echo $content | awk '{print $8}' FS='"')
    - echo ${url}
    - absolute_url=${CI_PROJECT_URL}${url}
    - curl --request POST --header "Content-Type:application/json" --header "Private-Token:MAzPbYT-xgaUgx2Nc4di" --data "{\"name\":\"Version $CI_COMMIT_REF_NAME\", \"tag_name\":\"$CI_COMMIT_REF_NAME\", \"ref\":\"$CI_COMMIT_REF_NAME\", \"description\":\"Release $CI_COMMIT_REF_NAME\", \"assets\":{ \"links\":[{ \"name\":\"Coordinator $CI_COMMIT_REF_NAME\", \"url\":\"${absolute_url}\"}]}}" "https://gitlab.com/api/v4/projects/18471086/releases"
    - content=$(curl --request POST --header "Private-Token:MAzPbYT-xgaUgx2Nc4di" --form "file=@/builds/Rett/coordinator/RecastDemo.rar" "https://gitlab.com/api/v4/projects/18471086/uploads")
    - echo ${content}
    - url=$(echo $content | awk '{print $8}' FS='"')
    - echo ${url}
    - absolute_url=${CI_PROJECT_URL}${url}
    - curl --request POST --header "Content-Type:application/json" --header "Private-Token:MAzPbYT-xgaUgx2Nc4di" --data "{\"name\":\"Version $CI_COMMIT_REF_NAME\", \"tag_name\":\"$CI_COMMIT_REF_NAME\", \"ref\":\"$CI_COMMIT_REF_NAME\", \"description\":\"Release $CI_COMMIT_REF_NAME\", \"assets\":{ \"links\":[{ \"name\":\"RecastDemo.rar\", \"url\":\"${absolute_url}\"}]}}" "https://gitlab.com/api/v4/projects/18471086/releases"